export { MainPage } from './src/main/ets/components/MainPage'
export * as CMessage from './src/main/protots/api/common/c_message'
export * as GGateway from './src/main/protots/gateway/g_gateway'
export * as GPayload from './src/main/protots/gateway/g_payload'
export * as GAction from './src/main/protots/gateway/g_action'
export { Chatlib, Resp, TeneasySDKDelegate } from './src/main/ets/lib/Chatlib';
export { LineDetectLib, Result } from './src/main/ets/lib/LineDetectLib';