/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 5.26.1
 * source: api/common/c_error_report.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../../google/protobuf/timestamp";
import * as dependency_2 from "./c_message";
import * as dependency_3 from "./../../google/protobuf/wrappers";
import * as pb_1 from "google-protobuf";
export namespace api.common {
    export enum CodeType {
        CodeType_DEFAULT = 0,
        CodeType_INTERFACE = 1,
        CodeType_GATEWAY = 2,
        CodeType_INTERNET = 3,
        CodeType_FRONTEND = 4
    }
    export enum Platform {
        Platform_DEFAULT = 0,
        Platform_IOS = 1,
        Platform_ANDROID = 2,
        Platform_H5 = 3,
        Platform_WEB_IOS = 4,
        Platform_WEB_WINDOWS = 5
    }
    export class ErrorReport extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            tenant_id?: number;
            url?: string;
            code?: number;
            payload?: string;
            code_type?: CodeType;
            ip?: string;
            platform?: Platform;
            created_at?: dependency_1.google.protobuf.Timestamp;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("tenant_id" in data && data.tenant_id != undefined) {
                    this.tenant_id = data.tenant_id;
                }
                if ("url" in data && data.url != undefined) {
                    this.url = data.url;
                }
                if ("code" in data && data.code != undefined) {
                    this.code = data.code;
                }
                if ("payload" in data && data.payload != undefined) {
                    this.payload = data.payload;
                }
                if ("code_type" in data && data.code_type != undefined) {
                    this.code_type = data.code_type;
                }
                if ("ip" in data && data.ip != undefined) {
                    this.ip = data.ip;
                }
                if ("platform" in data && data.platform != undefined) {
                    this.platform = data.platform;
                }
                if ("created_at" in data && data.created_at != undefined) {
                    this.created_at = data.created_at;
                }
            }
        }
        get tenant_id() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set tenant_id(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get url() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set url(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get code() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set code(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get payload() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set payload(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get code_type() {
            return pb_1.Message.getFieldWithDefault(this, 6, CodeType.CodeType_DEFAULT) as CodeType;
        }
        set code_type(value: CodeType) {
            pb_1.Message.setField(this, 6, value);
        }
        get ip() {
            return pb_1.Message.getFieldWithDefault(this, 7, "") as string;
        }
        set ip(value: string) {
            pb_1.Message.setField(this, 7, value);
        }
        get platform() {
            return pb_1.Message.getFieldWithDefault(this, 8, Platform.Platform_DEFAULT) as Platform;
        }
        set platform(value: Platform) {
            pb_1.Message.setField(this, 8, value);
        }
        get created_at() {
            return pb_1.Message.getWrapperField(this, dependency_1.google.protobuf.Timestamp, 9) as dependency_1.google.protobuf.Timestamp;
        }
        set created_at(value: dependency_1.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 9, value);
        }
        get has_created_at() {
            return pb_1.Message.getField(this, 9) != null;
        }
        static fromObject(data: {
            tenant_id?: number;
            url?: string;
            code?: number;
            payload?: string;
            code_type?: CodeType;
            ip?: string;
            platform?: Platform;
            created_at?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
        }): ErrorReport {
            const message = new ErrorReport({});
            if (data.tenant_id != null) {
                message.tenant_id = data.tenant_id;
            }
            if (data.url != null) {
                message.url = data.url;
            }
            if (data.code != null) {
                message.code = data.code;
            }
            if (data.payload != null) {
                message.payload = data.payload;
            }
            if (data.code_type != null) {
                message.code_type = data.code_type;
            }
            if (data.ip != null) {
                message.ip = data.ip;
            }
            if (data.platform != null) {
                message.platform = data.platform;
            }
            if (data.created_at != null) {
                message.created_at = dependency_1.google.protobuf.Timestamp.fromObject(data.created_at);
            }
            return message;
        }
        toObject() {
            const data: {
                tenant_id?: number;
                url?: string;
                code?: number;
                payload?: string;
                code_type?: CodeType;
                ip?: string;
                platform?: Platform;
                created_at?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
            } = {};
            if (this.tenant_id != null) {
                data.tenant_id = this.tenant_id;
            }
            if (this.url != null) {
                data.url = this.url;
            }
            if (this.code != null) {
                data.code = this.code;
            }
            if (this.payload != null) {
                data.payload = this.payload;
            }
            if (this.code_type != null) {
                data.code_type = this.code_type;
            }
            if (this.ip != null) {
                data.ip = this.ip;
            }
            if (this.platform != null) {
                data.platform = this.platform;
            }
            if (this.created_at != null) {
                data.created_at = this.created_at.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.tenant_id != 0)
                writer.writeInt32(2, this.tenant_id);
            if (this.url.length)
                writer.writeString(3, this.url);
            if (this.code != 0)
                writer.writeInt32(4, this.code);
            if (this.payload.length)
                writer.writeString(5, this.payload);
            if (this.code_type != CodeType.CodeType_DEFAULT)
                writer.writeEnum(6, this.code_type);
            if (this.ip.length)
                writer.writeString(7, this.ip);
            if (this.platform != Platform.Platform_DEFAULT)
                writer.writeEnum(8, this.platform);
            if (this.has_created_at)
                writer.writeMessage(9, this.created_at, () => this.created_at.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ErrorReport {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ErrorReport();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 2:
                        message.tenant_id = reader.readInt32();
                        break;
                    case 3:
                        message.url = reader.readString();
                        break;
                    case 4:
                        message.code = reader.readInt32();
                        break;
                    case 5:
                        message.payload = reader.readString();
                        break;
                    case 6:
                        message.code_type = reader.readEnum();
                        break;
                    case 7:
                        message.ip = reader.readString();
                        break;
                    case 8:
                        message.platform = reader.readEnum();
                        break;
                    case 9:
                        reader.readMessage(message.created_at, () => message.created_at = dependency_1.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ErrorReport {
            return ErrorReport.deserialize(bytes);
        }
    }
    export class ErrorReportUpload extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            url?: string;
            code?: number;
            payload?: string;
            ip?: string;
            platform?: Platform;
            created_at?: dependency_1.google.protobuf.Timestamp;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("url" in data && data.url != undefined) {
                    this.url = data.url;
                }
                if ("code" in data && data.code != undefined) {
                    this.code = data.code;
                }
                if ("payload" in data && data.payload != undefined) {
                    this.payload = data.payload;
                }
                if ("ip" in data && data.ip != undefined) {
                    this.ip = data.ip;
                }
                if ("platform" in data && data.platform != undefined) {
                    this.platform = data.platform;
                }
                if ("created_at" in data && data.created_at != undefined) {
                    this.created_at = data.created_at;
                }
            }
        }
        get url() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set url(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get code() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set code(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get payload() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set payload(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get ip() {
            return pb_1.Message.getFieldWithDefault(this, 7, "") as string;
        }
        set ip(value: string) {
            pb_1.Message.setField(this, 7, value);
        }
        get platform() {
            return pb_1.Message.getFieldWithDefault(this, 8, Platform.Platform_DEFAULT) as Platform;
        }
        set platform(value: Platform) {
            pb_1.Message.setField(this, 8, value);
        }
        get created_at() {
            return pb_1.Message.getWrapperField(this, dependency_1.google.protobuf.Timestamp, 9) as dependency_1.google.protobuf.Timestamp;
        }
        set created_at(value: dependency_1.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 9, value);
        }
        get has_created_at() {
            return pb_1.Message.getField(this, 9) != null;
        }
        static fromObject(data: {
            url?: string;
            code?: number;
            payload?: string;
            ip?: string;
            platform?: Platform;
            created_at?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
        }): ErrorReportUpload {
            const message = new ErrorReportUpload({});
            if (data.url != null) {
                message.url = data.url;
            }
            if (data.code != null) {
                message.code = data.code;
            }
            if (data.payload != null) {
                message.payload = data.payload;
            }
            if (data.ip != null) {
                message.ip = data.ip;
            }
            if (data.platform != null) {
                message.platform = data.platform;
            }
            if (data.created_at != null) {
                message.created_at = dependency_1.google.protobuf.Timestamp.fromObject(data.created_at);
            }
            return message;
        }
        toObject() {
            const data: {
                url?: string;
                code?: number;
                payload?: string;
                ip?: string;
                platform?: Platform;
                created_at?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
            } = {};
            if (this.url != null) {
                data.url = this.url;
            }
            if (this.code != null) {
                data.code = this.code;
            }
            if (this.payload != null) {
                data.payload = this.payload;
            }
            if (this.ip != null) {
                data.ip = this.ip;
            }
            if (this.platform != null) {
                data.platform = this.platform;
            }
            if (this.created_at != null) {
                data.created_at = this.created_at.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.url.length)
                writer.writeString(3, this.url);
            if (this.code != 0)
                writer.writeInt32(4, this.code);
            if (this.payload.length)
                writer.writeString(5, this.payload);
            if (this.ip.length)
                writer.writeString(7, this.ip);
            if (this.platform != Platform.Platform_DEFAULT)
                writer.writeEnum(8, this.platform);
            if (this.has_created_at)
                writer.writeMessage(9, this.created_at, () => this.created_at.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ErrorReportUpload {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ErrorReportUpload();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 3:
                        message.url = reader.readString();
                        break;
                    case 4:
                        message.code = reader.readInt32();
                        break;
                    case 5:
                        message.payload = reader.readString();
                        break;
                    case 7:
                        message.ip = reader.readString();
                        break;
                    case 8:
                        message.platform = reader.readEnum();
                        break;
                    case 9:
                        reader.readMessage(message.created_at, () => message.created_at = dependency_1.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ErrorReportUpload {
            return ErrorReportUpload.deserialize(bytes);
        }
    }
}
