/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 5.26.1
 * source: api/core/error_report.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../option";
import * as dependency_2 from "./../../google/protobuf/empty";
import * as dependency_3 from "./../../google/protobuf/timestamp";
import * as dependency_4 from "./../../validate/validate";
import * as dependency_5 from "./../common/c_base";
import * as dependency_6 from "./../common/c_error_report";
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace api.core {
    export class ErrorReportUploadRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            data?: dependency_6.api.common.ErrorReportUpload[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("data" in data && data.data != undefined) {
                    this.data = data.data;
                }
            }
        }
        get data() {
            return pb_1.Message.getRepeatedWrapperField(this, dependency_6.api.common.ErrorReportUpload, 1) as dependency_6.api.common.ErrorReportUpload[];
        }
        set data(value: dependency_6.api.common.ErrorReportUpload[]) {
            pb_1.Message.setRepeatedWrapperField(this, 1, value);
        }
        static fromObject(data: {
            data?: ReturnType<typeof dependency_6.api.common.ErrorReportUpload.prototype.toObject>[];
        }): ErrorReportUploadRequest {
            const message = new ErrorReportUploadRequest({});
            if (data.data != null) {
                message.data = data.data.map(item => dependency_6.api.common.ErrorReportUpload.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                data?: ReturnType<typeof dependency_6.api.common.ErrorReportUpload.prototype.toObject>[];
            } = {};
            if (this.data != null) {
                data.data = this.data.map((item: dependency_6.api.common.ErrorReportUpload) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.data.length)
                writer.writeRepeatedMessage(1, this.data, (item: dependency_6.api.common.ErrorReportUpload) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ErrorReportUploadRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ErrorReportUploadRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.data, () => pb_1.Message.addToRepeatedWrapperField(message, 1, dependency_6.api.common.ErrorReportUpload.deserialize(reader), dependency_6.api.common.ErrorReportUpload));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ErrorReportUploadRequest {
            return ErrorReportUploadRequest.deserialize(bytes);
        }
    }
    export class ErrorReportListRequest extends pb_1.Message {
        #one_of_decls: number[][] = [[10], [11]];
        constructor(data?: any[] | ({
            page?: dependency_5.api.common.Page;
            start_time?: dependency_3.google.protobuf.Timestamp;
            end_time?: dependency_3.google.protobuf.Timestamp;
            tenant_id?: number;
            url?: string;
            code?: number;
            code_type?: number;
            platform?: dependency_6.api.common.Platform;
            ip?: string;
            page_up_down?: dependency_5.api.common.PageUpDown;
        } & (({
            last_id?: number;
        }) | ({
            last_created_at?: dependency_3.google.protobuf.Timestamp;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("page" in data && data.page != undefined) {
                    this.page = data.page;
                }
                if ("start_time" in data && data.start_time != undefined) {
                    this.start_time = data.start_time;
                }
                if ("end_time" in data && data.end_time != undefined) {
                    this.end_time = data.end_time;
                }
                if ("tenant_id" in data && data.tenant_id != undefined) {
                    this.tenant_id = data.tenant_id;
                }
                if ("url" in data && data.url != undefined) {
                    this.url = data.url;
                }
                if ("code" in data && data.code != undefined) {
                    this.code = data.code;
                }
                if ("code_type" in data && data.code_type != undefined) {
                    this.code_type = data.code_type;
                }
                if ("platform" in data && data.platform != undefined) {
                    this.platform = data.platform;
                }
                if ("ip" in data && data.ip != undefined) {
                    this.ip = data.ip;
                }
                if ("last_id" in data && data.last_id != undefined) {
                    this.last_id = data.last_id;
                }
                if ("last_created_at" in data && data.last_created_at != undefined) {
                    this.last_created_at = data.last_created_at;
                }
                if ("page_up_down" in data && data.page_up_down != undefined) {
                    this.page_up_down = data.page_up_down;
                }
            }
        }
        get page() {
            return pb_1.Message.getWrapperField(this, dependency_5.api.common.Page, 1) as dependency_5.api.common.Page;
        }
        set page(value: dependency_5.api.common.Page) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        get has_page() {
            return pb_1.Message.getField(this, 1) != null;
        }
        get start_time() {
            return pb_1.Message.getWrapperField(this, dependency_3.google.protobuf.Timestamp, 2) as dependency_3.google.protobuf.Timestamp;
        }
        set start_time(value: dependency_3.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 2, value);
        }
        get has_start_time() {
            return pb_1.Message.getField(this, 2) != null;
        }
        get end_time() {
            return pb_1.Message.getWrapperField(this, dependency_3.google.protobuf.Timestamp, 3) as dependency_3.google.protobuf.Timestamp;
        }
        set end_time(value: dependency_3.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 3, value);
        }
        get has_end_time() {
            return pb_1.Message.getField(this, 3) != null;
        }
        get tenant_id() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set tenant_id(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get url() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set url(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get code() {
            return pb_1.Message.getFieldWithDefault(this, 6, 0) as number;
        }
        set code(value: number) {
            pb_1.Message.setField(this, 6, value);
        }
        get code_type() {
            return pb_1.Message.getFieldWithDefault(this, 7, 0) as number;
        }
        set code_type(value: number) {
            pb_1.Message.setField(this, 7, value);
        }
        get platform() {
            return pb_1.Message.getFieldWithDefault(this, 8, dependency_6.api.common.Platform.Platform_DEFAULT) as dependency_6.api.common.Platform;
        }
        set platform(value: dependency_6.api.common.Platform) {
            pb_1.Message.setField(this, 8, value);
        }
        get ip() {
            return pb_1.Message.getFieldWithDefault(this, 9, "") as string;
        }
        set ip(value: string) {
            pb_1.Message.setField(this, 9, value);
        }
        get last_id() {
            return pb_1.Message.getFieldWithDefault(this, 10, 0) as number;
        }
        set last_id(value: number) {
            pb_1.Message.setOneofField(this, 10, this.#one_of_decls[0], value);
        }
        get has_last_id() {
            return pb_1.Message.getField(this, 10) != null;
        }
        get last_created_at() {
            return pb_1.Message.getWrapperField(this, dependency_3.google.protobuf.Timestamp, 11) as dependency_3.google.protobuf.Timestamp;
        }
        set last_created_at(value: dependency_3.google.protobuf.Timestamp) {
            pb_1.Message.setOneofWrapperField(this, 11, this.#one_of_decls[1], value);
        }
        get has_last_created_at() {
            return pb_1.Message.getField(this, 11) != null;
        }
        get page_up_down() {
            return pb_1.Message.getFieldWithDefault(this, 12, dependency_5.api.common.PageUpDown.PUD_DEFAULT) as dependency_5.api.common.PageUpDown;
        }
        set page_up_down(value: dependency_5.api.common.PageUpDown) {
            pb_1.Message.setField(this, 12, value);
        }
        get _last_id() {
            const cases: {
                [index: number]: "none" | "last_id";
            } = {
                0: "none",
                10: "last_id"
            };
            return cases[pb_1.Message.computeOneofCase(this, [10])];
        }
        get _last_created_at() {
            const cases: {
                [index: number]: "none" | "last_created_at";
            } = {
                0: "none",
                11: "last_created_at"
            };
            return cases[pb_1.Message.computeOneofCase(this, [11])];
        }
        static fromObject(data: {
            page?: ReturnType<typeof dependency_5.api.common.Page.prototype.toObject>;
            start_time?: ReturnType<typeof dependency_3.google.protobuf.Timestamp.prototype.toObject>;
            end_time?: ReturnType<typeof dependency_3.google.protobuf.Timestamp.prototype.toObject>;
            tenant_id?: number;
            url?: string;
            code?: number;
            code_type?: number;
            platform?: dependency_6.api.common.Platform;
            ip?: string;
            last_id?: number;
            last_created_at?: ReturnType<typeof dependency_3.google.protobuf.Timestamp.prototype.toObject>;
            page_up_down?: dependency_5.api.common.PageUpDown;
        }): ErrorReportListRequest {
            const message = new ErrorReportListRequest({});
            if (data.page != null) {
                message.page = dependency_5.api.common.Page.fromObject(data.page);
            }
            if (data.start_time != null) {
                message.start_time = dependency_3.google.protobuf.Timestamp.fromObject(data.start_time);
            }
            if (data.end_time != null) {
                message.end_time = dependency_3.google.protobuf.Timestamp.fromObject(data.end_time);
            }
            if (data.tenant_id != null) {
                message.tenant_id = data.tenant_id;
            }
            if (data.url != null) {
                message.url = data.url;
            }
            if (data.code != null) {
                message.code = data.code;
            }
            if (data.code_type != null) {
                message.code_type = data.code_type;
            }
            if (data.platform != null) {
                message.platform = data.platform;
            }
            if (data.ip != null) {
                message.ip = data.ip;
            }
            if (data.last_id != null) {
                message.last_id = data.last_id;
            }
            if (data.last_created_at != null) {
                message.last_created_at = dependency_3.google.protobuf.Timestamp.fromObject(data.last_created_at);
            }
            if (data.page_up_down != null) {
                message.page_up_down = data.page_up_down;
            }
            return message;
        }
        toObject() {
            const data: {
                page?: ReturnType<typeof dependency_5.api.common.Page.prototype.toObject>;
                start_time?: ReturnType<typeof dependency_3.google.protobuf.Timestamp.prototype.toObject>;
                end_time?: ReturnType<typeof dependency_3.google.protobuf.Timestamp.prototype.toObject>;
                tenant_id?: number;
                url?: string;
                code?: number;
                code_type?: number;
                platform?: dependency_6.api.common.Platform;
                ip?: string;
                last_id?: number;
                last_created_at?: ReturnType<typeof dependency_3.google.protobuf.Timestamp.prototype.toObject>;
                page_up_down?: dependency_5.api.common.PageUpDown;
            } = {};
            if (this.page != null) {
                data.page = this.page.toObject();
            }
            if (this.start_time != null) {
                data.start_time = this.start_time.toObject();
            }
            if (this.end_time != null) {
                data.end_time = this.end_time.toObject();
            }
            if (this.tenant_id != null) {
                data.tenant_id = this.tenant_id;
            }
            if (this.url != null) {
                data.url = this.url;
            }
            if (this.code != null) {
                data.code = this.code;
            }
            if (this.code_type != null) {
                data.code_type = this.code_type;
            }
            if (this.platform != null) {
                data.platform = this.platform;
            }
            if (this.ip != null) {
                data.ip = this.ip;
            }
            if (this.last_id != null) {
                data.last_id = this.last_id;
            }
            if (this.last_created_at != null) {
                data.last_created_at = this.last_created_at.toObject();
            }
            if (this.page_up_down != null) {
                data.page_up_down = this.page_up_down;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_page)
                writer.writeMessage(1, this.page, () => this.page.serialize(writer));
            if (this.has_start_time)
                writer.writeMessage(2, this.start_time, () => this.start_time.serialize(writer));
            if (this.has_end_time)
                writer.writeMessage(3, this.end_time, () => this.end_time.serialize(writer));
            if (this.tenant_id != 0)
                writer.writeInt32(4, this.tenant_id);
            if (this.url.length)
                writer.writeString(5, this.url);
            if (this.code != 0)
                writer.writeInt32(6, this.code);
            if (this.code_type != 0)
                writer.writeInt32(7, this.code_type);
            if (this.platform != dependency_6.api.common.Platform.Platform_DEFAULT)
                writer.writeEnum(8, this.platform);
            if (this.ip.length)
                writer.writeString(9, this.ip);
            if (this.has_last_id)
                writer.writeUint64(10, this.last_id);
            if (this.has_last_created_at)
                writer.writeMessage(11, this.last_created_at, () => this.last_created_at.serialize(writer));
            if (this.page_up_down != dependency_5.api.common.PageUpDown.PUD_DEFAULT)
                writer.writeEnum(12, this.page_up_down);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ErrorReportListRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ErrorReportListRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.page, () => message.page = dependency_5.api.common.Page.deserialize(reader));
                        break;
                    case 2:
                        reader.readMessage(message.start_time, () => message.start_time = dependency_3.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    case 3:
                        reader.readMessage(message.end_time, () => message.end_time = dependency_3.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    case 4:
                        message.tenant_id = reader.readInt32();
                        break;
                    case 5:
                        message.url = reader.readString();
                        break;
                    case 6:
                        message.code = reader.readInt32();
                        break;
                    case 7:
                        message.code_type = reader.readInt32();
                        break;
                    case 8:
                        message.platform = reader.readEnum();
                        break;
                    case 9:
                        message.ip = reader.readString();
                        break;
                    case 10:
                        message.last_id = reader.readUint64();
                        break;
                    case 11:
                        reader.readMessage(message.last_created_at, () => message.last_created_at = dependency_3.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    case 12:
                        message.page_up_down = reader.readEnum();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ErrorReportListRequest {
            return ErrorReportListRequest.deserialize(bytes);
        }
    }
    export class ErrorReportListResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            page?: dependency_5.api.common.Page;
            list?: dependency_6.api.common.ErrorReport[];
            total?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("page" in data && data.page != undefined) {
                    this.page = data.page;
                }
                if ("list" in data && data.list != undefined) {
                    this.list = data.list;
                }
                if ("total" in data && data.total != undefined) {
                    this.total = data.total;
                }
            }
        }
        get page() {
            return pb_1.Message.getWrapperField(this, dependency_5.api.common.Page, 1) as dependency_5.api.common.Page;
        }
        set page(value: dependency_5.api.common.Page) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        get has_page() {
            return pb_1.Message.getField(this, 1) != null;
        }
        get list() {
            return pb_1.Message.getRepeatedWrapperField(this, dependency_6.api.common.ErrorReport, 2) as dependency_6.api.common.ErrorReport[];
        }
        set list(value: dependency_6.api.common.ErrorReport[]) {
            pb_1.Message.setRepeatedWrapperField(this, 2, value);
        }
        get total() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set total(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            page?: ReturnType<typeof dependency_5.api.common.Page.prototype.toObject>;
            list?: ReturnType<typeof dependency_6.api.common.ErrorReport.prototype.toObject>[];
            total?: number;
        }): ErrorReportListResponse {
            const message = new ErrorReportListResponse({});
            if (data.page != null) {
                message.page = dependency_5.api.common.Page.fromObject(data.page);
            }
            if (data.list != null) {
                message.list = data.list.map(item => dependency_6.api.common.ErrorReport.fromObject(item));
            }
            if (data.total != null) {
                message.total = data.total;
            }
            return message;
        }
        toObject() {
            const data: {
                page?: ReturnType<typeof dependency_5.api.common.Page.prototype.toObject>;
                list?: ReturnType<typeof dependency_6.api.common.ErrorReport.prototype.toObject>[];
                total?: number;
            } = {};
            if (this.page != null) {
                data.page = this.page.toObject();
            }
            if (this.list != null) {
                data.list = this.list.map((item: dependency_6.api.common.ErrorReport) => item.toObject());
            }
            if (this.total != null) {
                data.total = this.total;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_page)
                writer.writeMessage(1, this.page, () => this.page.serialize(writer));
            if (this.list.length)
                writer.writeRepeatedMessage(2, this.list, (item: dependency_6.api.common.ErrorReport) => item.serialize(writer));
            if (this.total != 0)
                writer.writeInt32(3, this.total);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ErrorReportListResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ErrorReportListResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.page, () => message.page = dependency_5.api.common.Page.deserialize(reader));
                        break;
                    case 2:
                        reader.readMessage(message.list, () => pb_1.Message.addToRepeatedWrapperField(message, 2, dependency_6.api.common.ErrorReport.deserialize(reader), dependency_6.api.common.ErrorReport));
                        break;
                    case 3:
                        message.total = reader.readInt32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ErrorReportListResponse {
            return ErrorReportListResponse.deserialize(bytes);
        }
    }
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedErrorReportService {
        static definition = {
            ErrorReportUpload: {
                path: "/api.core.ErrorReport/ErrorReportUpload",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: ErrorReportUploadRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => ErrorReportUploadRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_2.google.protobuf.Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_2.google.protobuf.Empty.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract ErrorReportUpload(call: grpc_1.ServerUnaryCall<ErrorReportUploadRequest, dependency_2.google.protobuf.Empty>, callback: grpc_1.sendUnaryData<dependency_2.google.protobuf.Empty>): void;
    }
    export class ErrorReportClient extends grpc_1.makeGenericClientConstructor(UnimplementedErrorReportService.definition, "ErrorReport", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        ErrorReportUpload: GrpcUnaryServiceInterface<ErrorReportUploadRequest, dependency_2.google.protobuf.Empty> = (message: ErrorReportUploadRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_2.google.protobuf.Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_2.google.protobuf.Empty>, callback?: grpc_1.requestCallback<dependency_2.google.protobuf.Empty>): grpc_1.ClientUnaryCall => {
            return super.ErrorReportUpload(message, metadata, options, callback);
        };
    }
    export abstract class UnimplementedAdminErrorReportService {
        static definition = {
            ErrorReportList: {
                path: "/api.core.AdminErrorReport/ErrorReportList",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: ErrorReportListRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => ErrorReportListRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: ErrorReportListResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => ErrorReportListResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract ErrorReportList(call: grpc_1.ServerUnaryCall<ErrorReportListRequest, ErrorReportListResponse>, callback: grpc_1.sendUnaryData<ErrorReportListResponse>): void;
    }
    export class AdminErrorReportClient extends grpc_1.makeGenericClientConstructor(UnimplementedAdminErrorReportService.definition, "AdminErrorReport", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        ErrorReportList: GrpcUnaryServiceInterface<ErrorReportListRequest, ErrorReportListResponse> = (message: ErrorReportListRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<ErrorReportListResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<ErrorReportListResponse>, callback?: grpc_1.requestCallback<ErrorReportListResponse>): grpc_1.ClientUnaryCall => {
            return super.ErrorReportList(message, metadata, options, callback);
        };
    }
}
